### ISSUE TITLE
Task doesn't appear in Preview

### ISSUE THREAD

**Issue by Mara-Li** [MrGlitchByte/obsidian_everforest#10]
The Task checkbox doesn't appear in preview mod. In tried with blank vault, both in light and dark : 
![image](https://user-images.githubusercontent.com/30244939/125869612-10d80751-e44a-4765-b396-086deeb79a5b.png)

**Comment by MrGlitchByte** [comment]
Fixed in most recent commit to main!

![task_highlight](https://user-images.githubusercontent.com/49317853/126055038-18faafef-7d34-415e-9255-0a4d3e367db8.PNG)
