### ISSUE TITLE
Active selection not highlighted in command palette and quick switcher

### ISSUE THREAD

**Issue by keybits** [MrGlitchByte/obsidian_everforest#2]
Thanks for a fantastic theme - my favorite Obsidian them 😄 

### Steps to reproduce this bug

Open the command palette or quick switcher in dark mode

### Actual behaviour

The active selection is not highlighted:

![image](https://user-images.githubusercontent.com/809823/125617561-6a5ae237-efeb-4c1c-8597-94fff8351575.png)

### Expected behaviour

The active selection is highlighted:

![image](https://user-images.githubusercontent.com/809823/125617615-21c13a3c-55a1-4e38-884a-fe18d2995dac.png)

Light mode does work, but the contrast is very slight so it's hard to see.

**Comment by MrGlitchByte** [comment]
Thanks for bringing this to my attention! It was pulling the wrong variable.

Should be fixed now for both light and dark modes.

![command-palette-fix-dark](https://user-images.githubusercontent.com/49317853/125628327-81a3ace7-0756-4291-bcfc-96cf51e7c326.PNG)

![command-palette-fix-light](https://user-images.githubusercontent.com/49317853/125628331-f3a55e0c-573c-46df-a5bd-04c49b5f4b60.PNG)

**Comment by keybits** [comment]
Perfect, thanks for the quick reply and fix!

Confirmed that resolves it for me.
