### ISSUE TITLE
The text of wikilinks is not very visible

### ISSUE THREAD

**Issue by kometenstaub** [MrGlitchByte/obsidian_everforest#6]
![image](https://user-images.githubusercontent.com/83140328/125693625-b4e7c3d2-c833-4804-b76f-64c8fae10bf4.png)

**Comment by MrGlitchByte** [comment]
Fixed the wikilink to be more readable in the latest push.

![Fixed wikilink](https://user-images.githubusercontent.com/49317853/125857542-d0a105e8-c7ab-4789-b898-a8af0b5a6ab6.PNG)
